<?php

function paragraphs_grid_theme($existing, $type, $theme, $path) {
  return array(
    'paragraphs_grid_content' => array(
      'render element' => 'element',
      'function' => 'paragraphs_grid_theme_paragraphs_grid_content',
    ),
  );
}

function paragraphs_grid_theme_paragraphs_grid_content($element) {
  $render = '';
  $render .= '<div class="wrapper">';
  $columns = 0;
  foreach ($element['items'] as $child) {
    // get the paragraphs key
    $pid = key($child['entity']['paragraphs_item']);
    // get the paragraphs item
    $item = &$child['entity']['paragraphs_item'][$pid];
    // use the column width
    $column_width = $item['#entity']->paragraphs_grid_column_width[LANGUAGE_NONE][0]['value'];
    // remove it from the render
    unset($item['paragraphs_grid_column_width']);
    $columns += (int) $column_width;
    if ($columns > 12) {
      $columns = $column_width;
      $render .= '</div><div class="wrapper">';
    }
    // add in the bundle name as a class
    $bundle = str_replace('_', '-', $item['#bundle']);
    $render .= '<div class="column-width-' . $column_width . ' ' . $bundle . '">';
    $render .= drupal_render($child);
    $render .= '</div>';
  }
  $render .= '</div>';
  return $render;
}

function paragraphs_grid_preprocess_field(&$vars) {
  if ($vars['element']['#field_type'] === 'paragraphs') {
    $has_columns = FALSE;

    foreach ($vars['items'] as $i => $paragraph) {
      $paragraph = array_shift($paragraph['entity']['paragraphs_item']);

      // If there are columns in this paragraph item, render the whole
      // paragraphs element as a grid.
      if (empty($paragraph['paragraphs_grid_column_width']) === FALSE) {
        $has_columns = TRUE;
        break;
      }
    }

    if ($has_columns === TRUE) {
      $vars['theme_hook_suggestions'][] = 'paragraphs_grid_content';
    }
  }
}

function paragraphs_grid_preprocess(&$vars, $hook) {
  if (isset($vars['elements']['#entity_type']) === TRUE) {
    if ($vars['elements']['#entity_type'] === 'paragraphs_item') {
      if (empty($vars['paragraphs_grid_column_width']) === FALSE) {
        $vars['classes_array'][] = 'column-' . $vars['paragraphs_grid_column_width'][0]['value'];
      }
    }
  }
}

/**
 * Update relevant paragraphs bundles to use the grid field
 * @param $bundles an array of paragraph bundle names that require column field
 */
function paragraphs_grid_configure_bundles($bundles) {
  // get bundles already using the field
  $current_field = field_info_field('paragraphs_grid_column_width');
  $old_bundles = isset($current_field['bundles']['paragraphs_item']) ? $current_field['bundles']['paragraphs_item'] : array();

  // remove old instances
  foreach($old_bundles as $bundle) {
    // anything in the old and not the new is removed
    if(in_array($bundle, $bundles) === FALSE) {
      // get the old instance
      $instance = field_info_instance('paragraphs_item', 'paragraphs_grid_column_width', $bundle);
      // second argument FALSE so field doesnt get removed from system
      field_delete_instance($instance, FALSE);
    }
  }

  // add new instances
  foreach($bundles as $bundle) {
    // anything in the new bundles not in the old was added
    if(in_array($bundle, $old_bundles) === FALSE) {
      $instance = array(
        'field_name' => 'paragraphs_grid_column_width',
        'entity_type' => 'paragraphs_item',
        'bundle' => $bundle,
        'label' => t('Column Width'),
        'required' => TRUE,
        'settings' => array(
          'min' => '1',
          'max' => '12',
        ),
        'default_value' => array(
          array('value' => '6'),
        ),
      );
      field_create_instance($instance);
    }
  }
}
